apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-app-deployment
  labels:
    app: cicd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-app
  template:
    metadata:
      labels:
        app: cicd-app
    spec:
      containers:
      - name: cicd-app
        image: amitabhdevops/cicd-app:0d61c87f84686d5ba478f3b278a528c52b64004a
        ports:
        - containerPort: 3000
